# Basics {#one}

## Day 1 (Monday) Zoom orientation

### Installing _R_ and _RStudio_ (25 minutes, Shawn)

BLAH BLAH BLAH. images, BLAH BLAH BLAH.

### Logistics (10 minutes, Adam)

Course material

- Available at https://mtmorgan.github.io/QuaRantine

Microsoft TEAMS

- Visit https://teams.microsoft.org and sign in with your Roswell username (e.g., `MA38727@RoswellPark.org` and the password you use to check email, etc.)
- Join the QuaRantine team

### Basics of _R_ (25 minutes, Martin)

A simple calculator

```{r}
1 + 2
```

Variables

Vectors

The versatile `data.frame`

Scripting


## Day 2

Creating a daily log of quarantine activities -- create a `data.frame` logging activities. Save to / read from a file.

## Day 3

Add to a `data.frame`. Basic statistical summary and visualization.

## Day 4

## Day 5 (Friday) Zoom check-in

Participant progress / challenges. Introduction to a COVID-19 data set documenting cases reported in the US.

### Review and trouble shoot (25 minutes)

### Next week (25 minutes)

## Day 6

Installing tidyverse

## Day 7

Input COVID-19 data. Statistical summary.
