# Machine learning {#four}

This week you will learn about machine learning for classification using _R_. Objectives are:

- To provide an overview of the underlying concepts of
machine learning for classification.

- To provide an introduction to some popular
classification algorithms.

- To explore these classification algorithms using various packages in _R_.

- To choose a classification algorithm and apply it to the statewide COVID-19 dataset.

## Day 22 (Monday) Zoom check-in

Here is an overview of what we'll cover in today's Zoom session:

- Overview of Machine Learning for Classification (30 minutes)

- Introduction to the Random Forests algorithm (5 minutes)

- A Random Forests Example in _R_ using Radiomics Data (25 minutes)

### A Machine Learning Primer

Machine Learning (ML) may be defined as using computers to make inferences about data.

- A mapping of inputs to outputs, Y = f(<b>X<b> , <b>β<b>)

- <i>ML for Classification</i> refers to algorithms that map inputs to a discrete set of outputs (i.e. classes or categories)

  - For example, predicting health risk (mild, moderate, severe) based on patient data (height, weight, age, smoker?)

  – Predictions are typically expressed as a vector of probabilities.
  
    – e.g. Pr(cancerous) vs. Pr(benign)

The diagram below illustrates the concept in terms of a "black box" model that converts inputs into predictions.

```{r echo=FALSE}
# insert ML figure
```

### Machine Learning Terminology

#### Features {-}

#### Parameters {-}

#### Labels {-}

#### Training Data {-}

#### Training {-}

#### Classification Accuracy {-}

#### Confusion Matrix {-}

#### ROC Curve {-}

#### AUC - Area Under the Curve {-}

### The Machine Learning Process

### The Random Forests Algorithm

### A Random Forests Example

## Day 23

For today's independent work you will learn about the Support Support Vector Machine (SVM) algorithm and apply it to the radiomics data that you worked with on Monday.

## Day 24

For today's independent work you will learn about the K-nearest neighbors (KNN) algorithm and apply it to the radiomics data.

## Day 25

For today's independent work you will learn about artificial neural networks (ANN). You will attempt to add Keras and TensorFlow support to your R/RStudio installation. If this turns out to be too dofficult, you will learn some "remote computing" alternatives that you can use in lieu of a local _R/Kera/TensorFlow_ installation. Finally, you'll apply `R-Keras-TensorFlow` to the radiomics example that you've been working with during the week.  

## Day 26 (Friday) Zoom check-in

### Review and trouble shoot (25 minutes)

### Next week (25 minutes)

## Day 27

## Day 28

Self-directed activities.
