# Collaboration {#six}

## 5 Days (Monday) Zoom check-in

### Weekend review (5 minutes)

### Vignettes (25 minutes; Shawn)

#### Vignette Preparation {-}

Create a small hierarcy of directories {-}

- `MyQuarantine` (top level)

    - `R` (inside `MyQuarantine`)

    - `vignettes` (also inside `MyQuarantine`)
    
```{r}
setwd("C:/temp")
dir.create("./MyQuarantine")
dir.create("./MyQuarantine/R")
dir.create("./MyQuarantine/vignette")
setwd("./MyQuarantine")
```
    
#### Create an `R markdown` document {-}

- `File` -> `New file` -> `R markdown...`

- Enter a `Title` and your name as `Author`

- Use `HTML` as default output

- _RStudio_ creates a template

  - save it (e.g., click the floppy disk icon) in the `vignettes` folder

#### Preview (knit) the markdown template {-}

- Click the `knit` button 

  -  install the `knitr` package if button is missing

#### Customize the template {-}

Let's add a demonstration of `ggplot2` using the `mtcars` data set:

```{}
---
title: "multiple regression plots"
author: "Shawn Matott"
date: "5/13/2020"
output: html_document
---

\```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
\```

## Muliple Regression Plots

- Scatterplot by category with regression lines (using ggplot2)

\```{r}
library(ggplot2)

data("mtcars")

# convert cyl to a factor-level object
mtcars$cyl = factor(
    mtcars$cyl,
    levels = c(4, 6, 8),
    labels = c("4 cyl", "6 cyl", "8 cyl")
)
>>>>>>> Stashed changes
    
ggplot(mtcars, aes(wt, mpg, color=cyl))+
    geom_point()+
    geom_smooth(method="lm")+
    labs(title="Regression of MPG on Weight by # Cylinders",
         x = "Weight",
         y = "Miles per Gallon",
         color = "Cylinders")
\```
```

#### Preview your edits {-}

- Save your changes

- Click the `knit` button 

After a bit of processing, the `Rmarkdown` is rendered as an `.html` page. Notice how the _R_ code block has been evaluated and resulting console output and plot are included in the `.html`. This is great because we can be sure that the vignette is actually working (e.g. no syntax errors or other coding problems).

There's a related package called `bookdown` that allows you to assemble documents and publish them directly to the web for all to see!

### Writing and documenting R functions (25 minutes)

## 4 Days Write a vignette!

## 3 Days Create documented, reusable functions!

## 2 Days Share your work as a package!

## Today! (Friday) Zoom check-in

Course review and next steps
