--- 
title: "40 Days and 40 Nights"
author: ["Martin Morgan", "L. Shawn Matott"]
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: |
    An ad hoc course to learn R for bioinformatics, using the 
    COVID-19 epidemic as an excuse.
---

# Motivation {-}

This is a WORK IN PROGRESS.

This course was suggested and enabled by Adam Kisailus and Richard Hershberger. It is available for Roswell Park graduate students.

## Introduction {-}

The word '[quarantine][]' is from the 1660's and refers to the fourty days (Italian _quaranta giorni_) a ship suspected of carrying disease was kept in isolation.

What to do in a quarantine? The astronaut Scott Kelly spent nearly a year on the International Space Station. In a New York Times [opinion piece][] he says, among other things, that 'you need a hobby', and what better hobby than a useful one? Let's take the opportunity provided by COVID-19 to learn R for statistical analysis and comprehension of data. Who knows, it may be useful after all this is over!

[quarantine]: https://www.etymonline.com/word/quarantine
[opinion piece]: https://www.nytimes.com/2020/03/21/opinion/scott-kelly-coronavirus-isolation.html

## What to expect {-}

We'll meet via zoom twice a week, Mondays and Thursdays, for one hour. We'll use this time to make sure everyone is making progress, and to introduce new or more difficult topics. Other days we'll have short exercises and activities that hopefully provide an opportunity to learn at your own speed.

We haven't thought this through much, but roughly we might cover:

- Week 1: In Chapter \ref{one} we'll start with the basics of installing and using R. We'll set up R and RStudio on your local computer, or if that doesn't work use a cloud-based RStudio. We'll learn the basics of R -- numeric, character, factor, and other vectors; variables; the `data.frame`; saving and reading data; basic data manipulation and visualization.

- Week 2: Packages for extending R. A great strenght of R is its extensibility through packages. We'll learn about [CRAN][], and install and use the 'tidyverse' suite of packages. We'll use publicly available data to explore the spread of COVID-19 in the US, including data manipulation and visualization.

- Week 3: Bioinformatic analysis with [Bioconductor][]. _Bioconductor_ is a collection of more than 1800 _R_ packages for the statistical analysis and comprehension of high-throughput genomic data. We'll use _Bioconductor_ to look at COVID-19 genome sequences, and to explore emerging genomic data relevant to the virus.

- Week 4: Independent projects. This week we'll get introspective, developing an analysis of data interesting to ourselves. We'll learn about writing 'markdown' reports to share our project with others.

- Week 5: Group projects. COVID-19 has really shown the value of open data and collaboration, so we'll tackle a group project where we each contribute to overall insights. We'll learn tools of collaboration including git and github, and develop 'best practices' for robust, reproducible research.

- Week 6: Sharing and end of QuaRantine! 40 days is 5 weeks and 5 days, so we should be wrapping up our 'hobby' in week 6. Let's summarize what we've done, and chart a path forward as we return to civilization!

[CRAN]: https://cran.r-project.org
[Bioconductor]: https://bioconductor.org
